### ISSUE TITLE
cat: checkSSTI.txt: No such file or directory

### ISSUE THREAD

**Issue by GiJ03** [R0X4R/Pinaak#1]
Getting this error everytime I am running the tool.
```
Getting all the parameters
Filtering all the parameters
cat: '~/ssti-payloads.txt': No such file or directory
cat: '~/lfi-payloads.txt': No such file or directory
Scanning for template based vulnerabilities
Checking injection attacks (may contains false positive)
cat: checkSSTI.txt: No such file or directory
cat: checkLFI.txt: No such file or directory
sed: no input files
```
![image](https://user-images.githubusercontent.com/57536491/120840498-f8c74d80-c587-11eb-935a-009dab6c7a59.png)

**Comment by R0X4R** [comment]
Hii @GiJ03,
Thanks for raising the issue.
Actually here I think the path of the payloads file is misplaced try finding these two files lfi-payloads and ssti-payloads or you can directly download these two files from https://github.com/R0X4R/Garud/tree/master/payloads and then set the correct path of your payloads in the pinaak.

Thanks,
R0X4R

**Comment by R0X4R** [comment]
Run these commands to fix it I pushed an update.
```bash
pinaak:~ mkdir -p ~/tools/payloads/
pinaak:~ cd ~/tools/payloads/
pinaak:~ wget https://raw.githubusercontent.com/R0X4R/Garud/master/payloads/lfi.txt
pinaak:~ wget https://raw.githubusercontent.com/R0X4R/Garud/master/payloads/ssti.txt
pinaak:~ wget https://raw.githubusercontent.com/R0X4R/Pinaak/master/pinaak && chmod +x pinaak && mv pinaak /usr/bin/
```

**Comment by rajatsharma1111** [comment]
@R0X4R 
After running the above commands as well, still, I am getting the below error
![image](https://user-images.githubusercontent.com/55489647/120846453-c6215300-c58f-11eb-82ad-067714999ce9.png)

**Comment by GiJ03** [comment]
After running the above commands, still I am getting the below error:
![image](https://user-images.githubusercontent.com/57536491/120846554-ecdf8980-c58f-11eb-9dc6-273b20e0dd84.png)

**Comment by R0X4R** [comment]
Try copy pasting the code. I think you have downloaded the cached version try copy pasting the code

**Comment by GiJ03** [comment]
Working perfectly now. Thanks alot! Really appreciate and thanks a lot for this awesome tool.
Just wanted to ask what is the difference between Pinaak and Garud?

**Comment by R0X4R** [comment]
Thank god it worked.
Actually Garud has limited tools and I made it for reconnaissance not for vulnerability scanning. But in pinaak I'll more tools to scan vulnerabilities. I made pinaak specially for vulnerability scanning.

**Comment by GiJ03** [comment]
So, if I am scanning a target using Pinaak, does it mean it will cover Garud as well? Or should I run Garud again?

**Comment by R0X4R** [comment]
Garud do subdomain scanning, directory fuzzing, web probing and more but Pinaak only scans for vulnerability. So if you have target lists and you just want to scan it's vulnerabilities you can simply run this so it can save your time

**Comment by GiJ03** [comment]
Got it. I believe running a scan using Garud, and then passing those list of subdomains to Pinaak, that will work.

**Comment by GiJ03** [comment]
Oops...I think something else broke now.

![image](https://user-images.githubusercontent.com/57536491/120848936-0d5d1300-c593-11eb-8d55-3f5f7757d5f3.png)

**Comment by R0X4R** [comment]
There's no need to run Garud for using pinaak. If you have target and you don't want to do recon like you have only 2 domains in scope so why you waste your time in running whole recon just simply put your target urls and then it will scan your targets also if you want multiple target domains to get scanned you can do that well. Like https://test.com https://target.com https://example.com, why you waste your time to recon for these single domain using Garud just run pinaak it will do your work and save your time.

**Comment by R0X4R** [comment]
The folder already exists that's why you getting this error always delete the old scan folder before running new scan in the same directory

**Comment by R0X4R** [comment]
> Oops...I think something else broke now.
> 
> ![image](https://user-images.githubusercontent.com/57536491/120848936-0d5d1300-c593-11eb-8d55-3f5f7757d5f3.png)

.

**Comment by GiJ03** [comment]
> There's no need to run Garud for using pinaak. If you have target and you don't want to do recon like you have only 2 domains in scope so why you waste your time in running whole recon just simply put your target urls and then it will scan your targets also if you want multiple target domains to get scanned you can do that well. Like https://test.com https://target.com https://example.com, why you waste your time to recon for these single domain using Garud just run pinaak it will do your work and save your time.

If I am scanning 3 different domains like example.com, test.com, victim.com. How the output will be created? In the separate folders i.e. example, test and victim or it will be clubbed into just 1?

**Comment by GiJ03** [comment]
Bro, there is some issue or the other is happening here.

![image](https://user-images.githubusercontent.com/57536491/120851506-890c8f00-c596-11eb-8adf-c9cc524a98fd.png)

**Comment by R0X4R** [comment]
It'll clubbed into just 1 file.

> > There's no need to run Garud for using pinaak. If you have target and you don't want to do recon like you have only 2 domains in scope so why you waste your time in running whole recon just simply put your target urls and then it will scan your targets also if you want multiple target domains to get scanned you can do that well. Like https://test.com https://target.com https://example.com, why you waste your time to recon for these single domain using Garud just run pinaak it will do your work and save your time.
> 
> If I am scanning 3 different domains like example.com, test.com, victim.com. How the output will be created? In the separate folders i.e. example, test and victim or it will be clubbed into just 1?

BTW sorry brother I slept yesterday so I replied you late.

**Comment by R0X4R** [comment]
The issue you faced with openredirx tool is because you're continuously running the tool again and again make sure to restart your system if you get these types of error.

Thanks.

**Comment by GiJ03** [comment]
If I am running this tool on VPS, where I am running 10 different tools as well in the background, in that case restarting the system will be an issue.
Can we resolve this error without restarting?
And just out of curiosity, why I am facing this error if I am scanning continuously? I am not running in parallel, but one after another.

**Comment by R0X4R** [comment]
> If I am running this tool on VPS, where I am running 10 different tools as well in the background, in that case restarting the system will be an issue.
> Can we resolve this error without restarting?
> And just out of curiosity, why I am facing this error if I am scanning continuously? I am not running in parallel, but one after another.

Hey, actually this is the issue with the [OpenRedireX](https://github.com/devanshbatham/OpenRedireX) itself. Just once restart your VPS this will fix the issue.

**Comment by GiJ03** [comment]
Yes, restarting VPS do fix it. But the issue is I have to start all the other tools as well from scratch.

**Comment by R0X4R** [comment]
> Yes, restarting VPS do fix it. But the issue is I have to start all the other tools as well from scratch.

Sorry for the problem you faced. I have pushed a new update that will hide the error if occurs.

**Comment by GiJ03** [comment]
Hiding the errors will not solve the errors right? The tool will stop working now as well right if I am running it continoulsy?

**Comment by R0X4R** [comment]
> Hiding the errors will not solve the errors right? The tool will stop working now as well right if I am running it continoulsy?

Yeah right, but other openredirection modules will help you to find the OpenRedirection bugs. So don't worry now the tool will work fine ;)

**Comment by GiJ03** [comment]
Hey bro, now getting this error. Which info file does it require now?
![image](https://user-images.githubusercontent.com/57536491/120899963-f03a4a00-c64f-11eb-84e5-008031a2999c.png)

**Comment by R0X4R** [comment]
Bro, don't worry tool is working fine. Your target has not matched the patterns so the file was not created if the target is vulnerable then it will not throw the error. Tool is working fine also if you want you can update it to latest push.
