### ISSUE TITLE
Gauplus got some bugs

### ISSUE THREAD

**Issue by Nithissh0708** [R0X4R/Pinaak#2]
![Screenshot_20210625-235633](https://user-images.githubusercontent.com/77142588/123469782-25afd300-d611-11eb-8c8c-128d7adedbc4.jpg)

**Comment by R0X4R** [comment]
Hi @Nithissh0708,
Actually  the issue is with your go-module try installing via source

```bash
gauplus:~ git clone https://github.com/bp0lr/gauplus.git && cd gaupplus
gauplus:~ go build . && cp gauplus /usr/bin/
```
Hope this will fix your issue :)

Thanks,
R0X4R
